---
- name: Community Call Dojo - Templates
  hosts: localhost
  connection: local
  vars:
    # Use this variable in your template. For testing purposes, add more members and re-run playbook.
    attendee_list:
      - Tim
      - Jonathan
  tasks:
    # pids-module needs psutil Python module, can be installed via package manager: python3-psutil
    # Install the package manually before executing the playbook!
    - name: Get process ID of Python HTTP server
      community.general.pids:
        pattern: .*http\.server.*
      register: python_webserver_pid

    # Use appropriate module to deploy template from templates-folder. Set the correct destination, look at
    # the last task were the webserver is started. The webserver expects a file named 'index.html' at the webserver root folder.
    - name: Deploy index.html template  # noqa syntax-check[specific]
      # ADD YOUR CODE HERE...

    # Don't change this task unless you have to use another port for your webserver
    - name: Run Python webserver
      ansible.builtin.shell:
        cmd: python3 -m http.server 8080 --directory /tmp &> /dev/null
        creates: /proc/{{ python_webserver_pid.pids | join(' ') }}/uid_map

    # The first condition only executes the command when a process ID is found (from first task)
    # The second condition is necessary to only execute the task when the tag is given, otherwise
    # the task is always executed (killing the webserver) when a webserver is running...
    - name: Stop Python webserver # noqa no-changed-when
      ansible.builtin.command:
        cmd: kill {{ python_webserver_pid.pids | join(' ') }}
      when:
        - python_webserver_pid.pids | length > 0
        - "'kill' in ansible_run_tags"
